version: '3' # We use version 3.5 syntax
services: # Here we define our service(s)
    angular-service: # The name of the service
      build: . # Location of our Dockerfile
      volumes: # Volume binding
        - "/app/node_modules"
        - ".:/app" 
      ports: 
        - '4200:4200' # Port mapping